source:
  image: PROJECT_NAME
  volumes:
    - /usr/src/app/venv
    - /usr/src/app/node_modules
    - /usr/src/app/static
  environment:
    - ENV=PROD
  env_file: prod.env
  command: scripts/install

web:
  image: PROJECT_NAME
  volumes_from:
    - source
  environment:
    - ENV=PROD
  env_file: prod.env
  command: gunicorn -b 0.0.0.0:8000 PROJECT_NAME.wsgi

nginx:
  image: nginx:latest
  ports:
    - 80:80
    - 443:443
  links:
    - web:web
  volumes:
    - nginx.conf:/etc/nginx/nginx.conf:ro
